kio: Autospec creation for update from version 5.102.0 to version 5.103.0
Alberto Mattea (1):
      Add missing copyFromFile entries to http.json for webdav and webdavs

Alexander Lohnau (1):
      KURISearchFilterEngine: Use DuckDuckGo as a default shortcut

Dāvis Mosāns (1):
      KCoreDirListerCache: Remove unnecessary assert

Friedrich W. H. Kossebau (18):
      Refer to worker in more debug logging
      Drop legacy flag USE_KPROCESS_FOR_KIOSLAVES
      Mark more implementation code related to deprecated "connected slave" feat.
      Remove unneeded includes of scheduler.h
      Deprecate Slave::isConnected/setConnected
      Remove private no-op slot Scheduler::slotSlaveOnHoldListChanged
      Switch to equivalent SlaveBase enums
      Remove unused include
      Deprecate unused Scheduler::connect/disconnects methods
      API docs: teach kapidox & ecm_add_qch about all possible deprecation macros
      Add deprecation warnings for KDirOperator::setView(KFile::FileView)
      Deprecation-wrap call of defunc PreviewJob::setOverlayIconAlpha()
      Use BUILD deprecation macros in non-public code
      PreviewJob: deprecation wrap implementation code for iconSize/iconAlpha
      Drop outdated docs for mailto kioslave
      Add deprecation markup to KPropertiesDialog::leaveModality
      Mark WorkerBase::needSubUrlData as deprecated
      Add KUrlNavigator::supportedSchemes, to replace customProtocols

Kai Uwe Broulik (1):
      KFilePlacesView: Set transientParent on context menu

Nate Graham (2):
      Correct setDesktopName() docs regarding optionality of .desktop suffix
      job_error: add missing space between sentences for one string

Nicolas Fella (2):
      Restore old behavior for KFileFilterCombo::setFilter
      [commandlauncherjob] Deprecate setIcon

Thenujan Sandramohan (1):
      CommandLauncher: Emit error when command was not found

Xaver Hugl (1):
      widgets/renamefiledialog: remove bulk rename number limit

l10n daemon script (31):
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Upgrade KF version to 5.103.0.
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      SVN_SILENT made messages (.desktop file) - always resolve ours
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      SVN_SILENT made messages (.desktop file) - always resolve ours
      GIT_SILENT Sync po/docbooks with svn
      SVN_SILENT made messages (.desktop file) - always resolve ours
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Upgrade ECM and KF version requirements for 5.103.0 release.